### PR TITLE
fix: changes in Spotify embeds

### LINKED ISSUE #94: Doesn't work anymore - Spotify changed their embeds.
**Describe the bug**
Doesn't work anymore - Spotify changed their embeds.

**Spotify URL(s)**
https://open.spotify.com/track/0Q0IVlqMV64kNLlwjPj0Hl?si=1b161308512e453f
https://open.spotify.com/track/0nhVrTiCGiGRCoZOJiWzm1?si=6c51f98fcb4140f4

**Your Code**
image
**Error Message**
Error: Couldn't find any data in embed page that we know how to parse
image

### PR DESCRIPTION
**Pull request by Eithoo**
image
(Closes #94)

### CODE REVIEW

**Comment by fmsidoe** [comment]
Good job Eithoo, only I do not get the album name of the track when using getDetails.

**Comment by Eithoo** [comment]
I don't know what's going on. I ran the test again a few minutes ago and it showed **3 tests failed**
image
Now I did it again without changing anything in the code and it's working normally:
image

**Comment by Eithoo** [comment]
> Good job Eithoo, only I do not get the album name of the track when using getDetails.

@fmsidoe I don't think new embeds return information about the track's album

**Comment by fmsidoe** [comment]
The embeds never showed album information, but **spotify-url-info** did showed album information when you use getTracks function. I was able to retrieve the album.name and album.release_date. Now it does not return any album fields

**Comment by Kikobeats** [comment]
Thanks for this great PR, some slightly changes:

- use `.find` over `.filter` to exit from the loop as soon as possible.
- dropped the hydration script since there aren't a test using it (probably Spotify is not using this way anymore)
- call `normalizeData` even that is not strictly necessary, it will be help us to detect new data types added by Spotify in the future.

How it looks to you? 🙂

**Comment by Eithoo** [comment]
I wanted to edit things while keeping original code style (not refactoring), that's why filter was used.
About hydration - I thought it was for some legacy style of embeds, so I left it there.

Nevertheless, your changes are great, LGTM 🙂

**Comment by Daviddavidov98** [comment]
BUMP on this 😭

File: src/index.js [hunk 1]
```diff
@@ -22,41 +22,35 @@ const createGetData = fetch => async (url, opts) => {
...
-    )
+  if (script !== undefined) {
+    // found data in the new embed style
+    const data = JSON.parse(
+      Buffer.from(decodeURIComponent(script.children[0].content), 'base64')
+    ).data.entity
+    // they removed/renamed some things, which for backwards compatibility we need to add back
+    data.external_urls = { spotify: spotifyURI.formatOpenURL(data.uri) }
+    data.release_date = data.releaseDate.isoString
+    data.audio = data.audioPreview.url
```
Comment (Kikobeats) [inline src/index.js:52]: @Eithoo why this backward compatibility is necessary?

Comment (Eithoo) [reply src/index.js]: Because they were returned by `getData` previously and should be there until the new major update (4.0.0) - someone might be using it in their project. I guess this fix is a minor/patch update, so everything should be backward compatible
https://semver.org/

Comment (Kikobeats) [reply src/index.js]: how do you know `release_date` and `audio` is being there, if isn't any assertion checking the value is there?

Comment (Kikobeats) [reply src/index.js]: I will be happy to accept this with the proper test assertions in a separate PR; For now, I'm going to remove these props for move this PR forward

**Comment by Kikobeats** [comment]
@fmsidoe if you find the way, consider make a PR 🙂

**Comment by Kikobeats** [comment]
@fmsidoe the problem with the album name is it isn't available in the web version:

CleanShot 2022-09-02 at 11 56 24@2x

You can just show it if you use the Spotify app.

If you find a way, please share with us 🙏
